### PR TITLE
Merge remote-tracking branch 'refs/remotes/greeniot/master'

### PR DESCRIPTION
**Pull request by rtheburger**
Added .pdf and .docx of the paper about Security in Embedded Computing

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Really? Please check again! I see 0 files changed. Am I missing something?

**Comment by rtheburger** [comment]
ahh sorry... Me as a github rookie trying to do something "on the go" does not seem to work.
Is my repository updated now?

**Comment by FlorianRappl** [comment]
Yep - but I don't want to merge it as-is ; ) (sorry!) - could you move the papers to `papers/` (from `presentations/`)?

Thanks!

**Comment by rtheburger** [comment]
like this? :)

**Comment by FlorianRappl** [comment]
Wonderful! Thanks 👍

**Pull request merged**
